import Head from 'next/head';
// import Image from 'next/image';
import Layout from '../components/Layout';
import styles from '../styles/Home.module.css';
import { css } from '@emotion/react';
import { useEffect } from 'react';
// import { useEffect } from 'react';

const color = css`
  color: #00a4e8;
`;

const image = css`
  border: 1px solid black;
  margin-top: 34px;
`;

export default function Home(props) {
  useEffect(() => {
    props.refreshUserProfile();
  }, [props]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Where are my pallets?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout userObject={props.userObject}>
        <main className={styles.main}>
          <h1 className={styles.welcome}>Welcome to </h1>{' '}
          <span css={color} className={styles.title}>
            Where are my pallets?
          </span>
          <h2>Your solution to keep track of the pallets you are changing.</h2>
          <img
            src="pal_man.jpg"
            alt="A man standing in front of a desk in a warehouse"
            height={700}
            width={1200}
            css={image}
          />
          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation </h2>
              <p>Save the delivery note as proof</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Tracking </h2>
              <p>Follow up in real time how many pallets you have in stock</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Driver contact </h2>
              <p>Possibility to send sms directly to the driver.</p>
            </a>
          </div>
        </main>

        <div>
          <h2>Image à inserer</h2>
        </div>
        <div>
          <h3> Info</h3>
          <h3> Blabla</h3>
        </div>
      </Layout>
    </div>
  );
}
